POST http://localhost:3333/objectives HTTP/1.1
Content-Type: application/json

{
    "title": "Teste",
    "goal": "3",
    "isDaily": true
}

#####

POST http://localhost:3333/objectives/progress HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjIzMjM4MjIsImV4cCI6MTY2MjkyODYyMiwic3ViIjoiOTFlMGNlMTMtMWM1Mi00ZDIwLThmY2UtMzJlZGIzZDdhZGJmIn0.7GyNOBasbsOW6ok5-C89AHIKUCTA82dQKhACJMJMEtU

{
    "objectiveId": "3462dd30-6ca7-486f-a2f8-daddc850a4ec",
    "progress": 1
}
