GET http://localhost:3333/contents HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjIzMjM4MjIsImV4cCI6MTY2MjkyODYyMiwic3ViIjoiOTFlMGNlMTMtMWM1Mi00ZDIwLThmY2UtMzJlZGIzZDdhZGJmIn0.7GyNOBasbsOW6ok5-C89AHIKUCTA82dQKhACJMJMEtU

#####

POST http://localhost:3333/contents HTTP/1.1
Content-Type: application/json

{
  "condition": 0,
  "messages": ["Olá", "E aí?", "Tá funcionando?"],
  "title": "Testando"
}
