POST http://localhost:3333/checkup HTTP/1.1
Content-Type: multipart/form-data; boundary=12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjQ1MDE2OTAsInN1YiI6IjViMTE3MTZkLTY1YTctNDdjYi04YTkyLTE1YTc3ZDUyNWViMyJ9.EZTvtc4ehV78OYUa6el9xWtQ8gIxiGhhxu8fKcm3U18

--12345
Content-Disposition: form-data; name="answers"
Content-Type: application/json

{
  "teste": 5
}

--12345
Content-Disposition: form-data; name="Boca de frente"; filename="test.png"
Content-Type: image/png

< ./tmp/test.png
--12345--
