POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
  "birthDate": "Sat Aug 20 2022 21:27:06 GMT-0300 (Brasilia Standard Time)",
  "chartNumber": "123",
  "city": "João Pessoa",
  "email": "hyoretsu@gmail.com",
  "name": "Aran",
  "neoplasia": "Câncer",
  "parentName": "Betto",
  "password": "segredo",
  "phoneNumber": "83996133794"
}
