GET http://localhost:3333/messages HTTP/1.1

#####

POST http://localhost:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjM3MDYzMDEsImV4cCI6MTY2NDMxMTEwMSwic3ViIjoiOTFlMGNlMTMtMWM1Mi00ZDIwLThmY2UtMzJlZGIzZDdhZGJmIn0.3ZT0JxqiL0Vj0-jdtpYjPf2NCXcjASkSgAfwH0m7SPU

{
  "body": "Olá senhor!",
  "recipientId": "5b11716d-65a7-47cb-8a92-15a77d525eb3"
}
